apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-conf
spec: 
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "name": "ipvlan",
      "master": "enp0s3",
      "mode": "l2",
      "ipam": {
        "type": "host-local",
        "subnet": "10.5.2.0/24",
        "rangeStart": "10.5.2.200",
        "rangeEnd": "10.5.2.254",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.5.2.1"
      }
    }'
